SELECT ?l ?c ?vf ?lg ?c1
WHERE {
  ?p rdfs:label ?l .
  ?p xmpl:propertyText1 ?pt .
  ?p mo:producer ?pcr .
  ?pcr edm:country ?c .
  ?pcr foaf:homepage ?h .
  ?o gr:validFrom ?vf .
  ?o bbc:product ?p .
  ?r bbc:product ?p .
  ?r dbpedia-owl:person ?pr .
  ?r dcterms:language ?lg .
  ?pr edm:country ?c1 .
  ?pr a foaf:Person .
  FILTER (?c = "'DE'") .
  TRANSFORM (?r?pr.r.replc("ID","").toInt && ?p?pcr.r.scl(-109))
}
